<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\Dtos\**" />
    <Compile Remove="Services\Policy\**" />
    <EmbeddedResource Remove="Services\Dtos\**" />
    <EmbeddedResource Remove="Services\Policy\**" />
    <None Remove="Services\Dtos\**" />
    <None Remove="Services\Policy\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClipBeam.Domain\ClipBeam.Domain.csproj" />
  </ItemGroup>

</Project>
